# Default values for observability-stack
# This is a YAML-formatted file.

# Namespace configuration
namespace: observability

# OpenTelemetry Collector
otelCollector:
  enabled: true
  image:
    repository: otel/opentelemetry-collector-contrib
    tag: 0.91.0
    pullPolicy: IfNotPresent
  replicas: 2
  resources:
    requests:
      memory: "256Mi"
      cpu: "100m"
    limits:
      memory: "512Mi"
      cpu: "500m"
  service:
    type: ClusterIP
    ports:
      otlpGrpc: 4317
      otlpHttp: 4318
      prometheus: 8889
      metrics: 8888

# Prometheus
prometheus:
  enabled: true
  image:
    repository: prom/prometheus
    tag: v2.48.0
    pullPolicy: IfNotPresent
  replicas: 1
  retention: 15d
  retentionSize: 10GB
  resources:
    requests:
      memory: "512Mi"
      cpu: "200m"
    limits:
      memory: "2Gi"
      cpu: "1000m"
  service:
    type: ClusterIP
    port: 9090
  storage:
    enabled: false
    size: 20Gi
    storageClassName: standard

# Jaeger
jaeger:
  enabled: true
  image:
    repository: jaegertracing/all-in-one
    tag: "1.52"
    pullPolicy: IfNotPresent
  replicas: 1
  storage:
    type: memory  # memory, cassandra, elasticsearch
  resources:
    requests:
      memory: "256Mi"
      cpu: "100m"
    limits:
      memory: "1Gi"
      cpu: "500m"
  service:
    type: ClusterIP
    uiPort: 16686
    collectorPort: 14250

# Grafana
grafana:
  enabled: true
  image:
    repository: grafana/grafana
    tag: 10.2.2
    pullPolicy: IfNotPresent
  replicas: 1
  adminUser: admin
  adminPassword: admin
  resources:
    requests:
      memory: "128Mi"
      cpu: "100m"
    limits:
      memory: "512Mi"
      cpu: "500m"
  service:
    type: ClusterIP
    port: 3000
  storage:
    enabled: false
    size: 5Gi
    storageClassName: standard

# Sample Applications
backend:
  enabled: true
  image:
    repository: backend
    tag: latest
    pullPolicy: Never
  replicas: 2
  resources:
    requests:
      memory: "128Mi"
      cpu: "100m"
    limits:
      memory: "256Mi"
      cpu: "500m"
  service:
    type: ClusterIP
    port: 8080

frontend:
  enabled: true
  image:
    repository: frontend
    tag: latest
    pullPolicy: Never
  replicas: 2
  resources:
    requests:
      memory: "128Mi"
      cpu: "100m"
    limits:
      memory: "256Mi"
      cpu: "500m"
  service:
    type: ClusterIP
    port: 8080

# Global settings
global:
  environment: development
  clusterName: minikube
