apiVersion: v1
kind: Service
metadata:
  name: frontend
  labels:
    app: frontend
    tier: application
spec:
  type: ClusterIP
  selector:
    app: frontend
  ports:
  - name: http
    port: 8080
    targetPort: 8080
    protocol: TCP
