apiVersion: v1
kind: ConfigMap
metadata:
  name: grafana-datasources
  namespace: observability
  labels:
    app: grafana
data:
  datasources.yaml: |
    apiVersion: 1
    
    datasources:
      # Prometheus datasource
      - name: Prometheus
        type: prometheus
        access: proxy
        url: http://prometheus.observability.svc.cluster.local:9090
        isDefault: true
        editable: true
        jsonData:
          timeInterval: 15s
          queryTimeout: 60s
          httpMethod: POST
      
      # Jaeger datasource
      - name: Jaeger
        type: jaeger
        access: proxy
        url: http://jaeger-query.observability.svc.cluster.local:16686
        editable: true
        jsonData:
          tracesToLogs:
            datasourceUid: 'loki'
            tags: ['job', 'instance', 'pod', 'namespace']
          nodeGraph:
            enabled: true
      
      # Loki datasource (optional - for logs)
      # - name: Loki
      #   type: loki
      #   access: proxy
      #   url: http://loki.observability.svc.cluster.local:3100
      #   editable: true
