apiVersion: v1
kind: Service
metadata:
  name: backend
  labels:
    app: backend
    tier: application
spec:
  type: ClusterIP
  selector:
    app: backend
  ports:
  - name: http
    port: 8080
    targetPort: 8080
    protocol: TCP
